services:
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PRODUTION = True
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  pgdata: