app = 'copia-todoist'
primary_region = 'gru'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  FLET_SESSION_TIMEOUT = '60'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
